services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'meal-registration'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - /RocketSeat/Python/Daily_Diet_API:/var/lib/mysql